# Generated by Django 5.2.5 on 2025-08-24 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npoint_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONData',
            fields=[
                ('json_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('json_picture', models.ImageField(blank=True, null=True, upload_to='json_pictures/')),
                ('json_content', models.JSONField()),
                ('json_api', models.CharField(blank=True, null=True, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
