# Generated by Django 5.2.5 on 2025-08-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npoint_app', '0002_jsondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AddConstraint(
            model_name='jsondata',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='uniq_user_slug'),
        ),
    ]
