# Generated by Django 5.2.5 on 2025-09-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npoint_app', '0004_passwordresetcode_alter_jsondata_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='json_api',
            field=models.CharField(blank=True, null=True),
        ),
    ]
